site_name: SkidKit
site_url: https://basil.is-a.dev/SkidKit
site_description: Documentation and articles pertaining to SkidKit
site_author: Basilicous
copyright: © 2021 Basilicous.  All rights reserved.

nav:
  - Home: index.md
  - "How to make a mixin client":
    - "1 | Introduction": "MixinClientTutorial/introduction.md"
    - "2 | Setting up": "MixinClientTutorial/setting_up.md"
    - "3 | Making a tweaker": "MixinClientTutorial/tweaker.md"
    - "4 | Our first mixin": "MixinClientTutorial/first_mixin.md"
  - "Interface Component": 
    - "About": InterfaceComponent/interface_component.md
    - "Layouts": InterfaceComponent/layouts.md
    - "Box Model": InterfaceComponent/box_model.md
    - "Stylesheets": InterfaceComponent/stylesheets.md
    - "Surfaces & Elements": InterfaceComponent/surfaces_and_elements.md
  - "Articles":
    - "Minecraft and C++": "articles/minecraft_and_cpp.md"
    - "Sumo takes skill": "articles/sumo_takes_skill.md"

theme:
  name: material
  nav_style: dark

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js